Outputs:
  webserverPublicIp:
    Value : !Sub ${webserver.PublicIp}

Resources:
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: nothing
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        -
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
  webserver:
    Type: AWS::EC2::Instance
    Metadata:
      AWS:CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []

          services:
            sysvinint:
              httpd:
                enabled: true
                ensureRunning: true

    Properties:
     ImageId: ami-467ca739
     InstanceType: m4.large
     SecurityGroups:
      - !Ref securityGroup
     UserData:
      Fn::Base64:
        !Sub |
          #!/bin/bash -xe
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -s ${AWS::StackId} -r webserver  --region ${AWS::Region}
     KeyName: pka